server:
  port: 8888
spring:
  application:
    #应用名字
    name: duowen-sms-rabbitmq

  #rabbitmq的配置
  rabbitmq:
    host: 192.168.42.129
    port: 5672
    username: admin
    password: admin
    virtual-host: /

logging:
  level: info
# error日志输出
#log4j.appender.errorfile=org.apache.log4j.DailyRollingFileAppender
#log4j.appender.errorfile.file=logs/error.log
#log4j.appender.errorfile.DatePattern='.'yyyy-MM-dd
#log4j.appender.errorfile.Threshold = ERROR
#log4j.appender.errorfile.layout=org.apache.log4j.PatternLayout
#log4j.appender.errorfile.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %5p %c{1}:%L - %m%n
